# Generated by Django 3.2.2 on 2022-05-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atransaction',
            old_name='type',
            new_name='transaction_type',
        ),
    ]
